# Generated by Django 5.0.7 on 2024-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportname', models.CharField(blank=True, max_length=20, null=True)),
                ('to', models.CharField(blank=True, max_length=355, null=True)),
                ('cc', models.CharField(blank=True, max_length=355, null=True)),
                ('bcc', models.CharField(blank=True, max_length=355, null=True)),
            ],
        ),
    ]
